### PR TITLE
added raspbian-portal project

### PR DESCRIPTION
**Pull request by dhurley14**
added a few scripts to setup a PORTALofPi using raspbian when someone can't get a copy of arch linux onto their raspberry pi.

### CODE REVIEW

**Comment by grugq** [comment]
My concerns with using raspian are that there are just so many weird services and other things that it is hard to ensure the RaspberryPi device itself is secure. 

The reason that I chose Arch initially was to create a minimal environment with only the tools specifically required to take the device online and to make the Tor daemon functional. After that, I wanted to have basically nothing. With no additional applications, the attack surface of the PORTAL is minimal.

I understand that in terms of appeal to a broader userbase having support for Raspian is definitely important. But I want to make sure that the Raspbian install is hardened against attack. I am not familiar enough with what Raspbian installs and does to know what needs to be done to harden it.

At a minimum what I would want to see is:
1. No additional services running
   - ensure that there are no open ports (other than Tor)
   - ensure that there are no running services that connect out to anything (see below)
2. Remove/strip unnecessary packages
   - I understand  that X11 and some other user friendly packages are installed. These should be gone.
   - I am not familiar with how Raspbian does network configuration, if the X11 packages are required, that complicates matters... How long until theres Firefox running as well? I'm concerned about the PORTAL being compromised
3. Automatic updates
   - there are some automatic update features on Raspbian. They are exempt from "no external contact" but it should be noted that there shouldn't be much software needed to run a PORTAL device

If there is a guide/script on hardening Raspbian, pointing to that as a pre-requisite for the install is ok (as long as the above issues are addressed in some way: minimize attack surface; reduce capability for user to make fatal errors due to enabling risky behavior; enable secure auto update)

**Comment by grugq** [comment]
Some additional feedback in terms of the network setup that this set of patches introduces.

### Packet Forwarding

The `sysctl.conf` enables packet forwarding. This is a security risk as it allows the PORTAL to fail open if the Tor daemon or the iptables rules fail. The Tor daemon handles to forwarding for the network connection by itself, so there is no need for packet forwarding at the kernel layer.

For security purposes, disable packet forwarding. 

### IPTables Permissiveness

The `iptables` rule set must block everything by default. The only rules it should have are transparent forwarding for DNS requests to Tor, and for TCP connections to Tor. This means that there is no way for any data of any sort to exit the WiFi network unless it is handled by Tor. If there is an error with Tor (or whatever) then the WiFi network will fail closed and the user will be unable to connect. This prevents fatal errors.

From the looks of it, the `iptables` rules in this PR are not restrictive enough. Please lock them down further. 

### sshd configuration

There is a problem with the RPi as a platform (it has way too few access options). The exposed `sshd` allows any malicious user on the network to access the PORTAL and modify the configuration, exposing the user to danger. Even with password protection, the risk is too high (users pick crappy passwords, and a compromised device on the network could allow an attacker to harvest credentials or hijack an existing session)

**Comment by dhurley14** [comment]
Okay this is awesome.  Thank you for the feedback!  I'll start looking to fix these issues.  I'm pretty new to any sort of network security stuff so I apologize for not thinking about your comments above before hand.    I'll reopen this pull request when I think I've managed to sufficiently harden the pi.

Thanks again for the feedback!

**Comment by grugq** [comment]
Thanks for working on Raspbian support. It will definitely help to make PORTAL available to more people.

The above notes should help guide you in what needs to be done to make it a reality.

Please send a new PR when you think you have addressed those points. 

Good luck!

**Comment by grugq** [comment]
# Raspbian PORTAL Design Guide
1. Harden OS
   - install the Tor daemon (any other requirements)
   - minimize attack surface
   - remove unnecessary packages
   - disable all non essential services
   - ensure automatic security updates are applied
2. Configure Network
   - disable packet forwarding
   - create WiFi "Tor" zone
   - lock down `iptables` ruleset + enable Tor proxying
3. Device Admin
   - allow device administration from console access only (after setup)
   - this means that unless the user is physically located at the device, they are unable to alter the config

I believe that should be most of the things necessary to make the Raspbian version.

**Comment by dhurley14** [comment]
This is awesome thanks for this guide!  I'll be working to cross these off over the next few weeks.  Thanks!  Looking forward to making this happen 👍

**Pull request closed without merging**
